### ISSUE TITLE
Cortex build - two RMAN_ROOT flags

### ISSUE THREAD

**Issue by HughMacdonald** [johnhaddon/gafferDependencies#6]
I'm just trying to figure out what I need to do a full dependencies build myself, and came across this one.

Both
https://github.com/johnhaddon/gafferDependencies/blob/master/build/buildCortex.sh#L33
and
https://github.com/johnhaddon/gafferDependencies/blob/master/build/buildCortex.sh#L36
list RMAN_ROOT, one setting it to $DELIGHT (which is not a required env var in buildAll.sh) and the other to $RMAN_ROOT, which is required.

**Comment by johnhaddon** [comment]
I suspect the DELIGHT one will be bogus then - I have it set in my shell here by default and probably came to rely on it somehow. Can you give things a go having removed it?

**Comment by HughMacdonald** [comment]
It looks like it's overridden by $RMAN_ROOT, but would error if $DELIGHT wasn't set.

I'm a way off being able to built it - don't have 3Delight or Arnold installed here...

**Comment by johnhaddon** [comment]
Closing this since it appears to have been fixed.
